name: Docker (tag:Release)

on:
  push:
    tags: [ "*" ]

jobs:
  push_fpm:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
  
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0']

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug
        
    - uses: actions/checkout@v2
      
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3.6.0
      with:
        images: ghcr.io/vaop/php-fpm
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      id: docker
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .build/php-fpm/
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: .build/php-fpm/Dockerfile
        build-args: |
          UPSTREAM_TAG=${{ matrix.php-versions }}-fpm-alpine
